// Code generated by mockery v2.10.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	voting "github.com/rfdez/voting-poll/internal"
	mock "github.com/stretchr/testify/mock"
)

// PollRepository is an autogenerated mock type for the PollRepository type
type PollRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, poll
func (_m *PollRepository) Save(ctx context.Context, poll voting.Poll) error {
	ret := _m.Called(ctx, poll)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, voting.Poll) error); ok {
		r0 = rf(ctx, poll)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
