name: Integration tests
on:
  push:
    branches:
      - main

env:
  GOLANG_VERSION: '1.18'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-go:
    name: Ensure Go modules syncrhonicity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Download all Go modules
        run: |
          go mod download
      - name: Check for tidyness of go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- .
      - name: Verify Go modules
        run: |
          go mod verify

  build-go:
    name: Build and cache Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Restore Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v2-${{ github.run_id }}
      - name: Download all Go modules
        run: |
          go mod download
      - name: Compile all packages
        run: |
          go build -v $(go list ./... | grep -v /vendor/ | tr '\n' ' ')

  lint-go:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: --timeout 10m --verbose

  test-go:
    name: Test Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Install required packages
        run: |
          go install gotest.tools/gotestsum@v1.8.1
          go install github.com/t-yuki/gocover-cobertura@v0.0.0-20180217150009-aaee18c8195c
      - name: Run gotestsum
        run: |
          gotestsum --junitfile go_test.xml --format testname -- -short -race -coverprofile coverage.txt -covermode atomic -buildvcs=false $(go list ./... | grep -v /vendor/ | tr '\n' ' ')
      - name: Prepare code coverage artifact
        run: |
          gocover-cobertura < coverage.txt > coverage.xml
          sed -i 's;filename=\"github.com/rfdez/voting-poll/;filename=\";g' coverage.xml
      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.xml
          retention-days: 3
      - name: Upload tests result
        uses: actions/upload-artifact@v3
        with:
          name: tests-result
          path: go_test.xml
          retention-days: 3
      - name: Upload code coverage information to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: coverage.txt
