name: Create release
on:
  push:
    tags:
      - "*"

jobs:
  prepare-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup vars
        run: |
          PRE_RELEASE=true
          if [[ ${{ github.event.ref }} =~ ^refs/tags/(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$ ]]; then
            PRE_RELEASE=false
          fi

          echo "PRE_RELEASE=${PRE_RELEASE}" >> $GITHUB_ENV
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          prerelease: ${{ env.PRE_RELEASE }}
